# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\" \n\x0fIdentifyRequest\x12\r\n\x05Token\x18\x01 \x01(\t\"\n\n\x08GetState\"\t\n\x07GetInfo\"\"\n\x08SetState\x12\x16\n\x05state\x18\x01 \x01(\x0e\x32\x07.States\"\xc9\x01\n\x05State\x12\x1d\n\x08light_on\x18\x01 \x01(\x0e\x32\x0b.LighStates\x12\"\n\tdoor_lock\x18\x02 \x01(\x0e\x32\x0f.DoorLockStates\x12!\n\tchannel_1\x18\x03 \x01(\x0e\x32\x0e.ChannelStates\x12!\n\tchannel_2\x18\x04 \x01(\x0e\x32\x0e.ChannelStates\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x10\n\x08pressure\x18\x06 \x01(\x02\x12\x10\n\x08humidity\x18\x07 \x01(\x02\"@\n\x04Info\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x10\n\x08\x62le_name\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"x\n\rClientMessage\x12\x1c\n\x08get_info\x18\x01 \x01(\x0b\x32\x08.GetInfoH\x00\x12\x1e\n\tset_state\x18\x02 \x01(\x0b\x32\t.SetStateH\x00\x12\x1e\n\tget_state\x18\x03 \x01(\x0b\x32\t.GetStateH\x00\x42\t\n\x07message\"m\n\x12\x43ontrollerResponse\x12\x15\n\x04info\x18\x01 \x01(\x0b\x32\x05.InfoH\x00\x12\x17\n\x05state\x18\x02 \x01(\x0b\x32\x06.StateH\x00\x12\x1b\n\x06status\x18\x03 \x01(\x0e\x32\t.StatusesH\x00\x42\n\n\x08response*\x1d\n\x08Statuses\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01*\x1d\n\nLighStates\x12\x06\n\x02On\x10\x00\x12\x07\n\x03Off\x10\x01*%\n\x0e\x44oorLockStates\x12\x08\n\x04Open\x10\x00\x12\t\n\x05\x43lose\x10\x01*.\n\rChannelStates\x12\r\n\tChannelOn\x10\x00\x12\x0e\n\nChannelOff\x10\x01*\x8a\x01\n\x06States\x12\x0b\n\x07LightOn\x10\x00\x12\x0c\n\x08LightOff\x10\x01\x12\x10\n\x0c\x44oorLockOpen\x10\x02\x12\x11\n\rDoorLockClose\x10\x03\x12\x0e\n\nChannel1On\x10\x04\x12\x0f\n\x0b\x43hannel1Off\x10\x05\x12\x0e\n\nChannel2On\x10\x06\x12\x0f\n\x0b\x43hannel2Off\x10\x07\x42\x08Z\x06./;apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./;api'
  _globals['_STATUSES']._serialized_start=616
  _globals['_STATUSES']._serialized_end=645
  _globals['_LIGHSTATES']._serialized_start=647
  _globals['_LIGHSTATES']._serialized_end=676
  _globals['_DOORLOCKSTATES']._serialized_start=678
  _globals['_DOORLOCKSTATES']._serialized_end=715
  _globals['_CHANNELSTATES']._serialized_start=717
  _globals['_CHANNELSTATES']._serialized_end=763
  _globals['_STATES']._serialized_start=766
  _globals['_STATES']._serialized_end=904
  _globals['_IDENTIFYREQUEST']._serialized_start=20
  _globals['_IDENTIFYREQUEST']._serialized_end=52
  _globals['_GETSTATE']._serialized_start=54
  _globals['_GETSTATE']._serialized_end=64
  _globals['_GETINFO']._serialized_start=66
  _globals['_GETINFO']._serialized_end=75
  _globals['_SETSTATE']._serialized_start=77
  _globals['_SETSTATE']._serialized_end=111
  _globals['_STATE']._serialized_start=114
  _globals['_STATE']._serialized_end=315
  _globals['_INFO']._serialized_start=317
  _globals['_INFO']._serialized_end=381
  _globals['_CLIENTMESSAGE']._serialized_start=383
  _globals['_CLIENTMESSAGE']._serialized_end=503
  _globals['_CONTROLLERRESPONSE']._serialized_start=505
  _globals['_CONTROLLERRESPONSE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
